version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    networks:
      - nginx_mulit_config  
    ports:
      - '6379:6379'
  ui:
    build: ./ui
    networks:
      - nginx_mulit_config
    restart: on-failure
    ports:
      - '3000:3000'
  file_server:
    build: ./file_server
    networks:
      - nginx_mulit_config
    restart: on-failure
    ports:
      - '5001:5001'
    volumes:
      - ${DATA_FOLDER}:/server
  auth_server:
    build: ./auth_server
    networks:
      - nginx_mulit_config
    restart: on-failure
    ports:
      - '5002:5002'
    volumes:
      - ${DATA_FOLDER}:/server      
  nginx:
    build: ./nginx
    networks:
      - nginx_mulit_config
    restart: on-failure
    ports:
    - '80:80'
    depends_on:
    - ui
    - file_server
    - auth_server

networks:
  nginx_mulit_config:


volumes:
  data_folder: